#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

void solve(long long N, long long A, long long B, std::vector<long long> C)
{
    for (int i = 0; i < N; i++)
    {
        if (C[i] == A + B)
        {
            cout << i + 1 << endl;
        }
    }
}

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    long long N;
    std::scanf("%lld", &N);
    long long A;
    std::scanf("%lld", &A);
    long long B;
    std::scanf("%lld", &B);
    std::vector<long long> C(N);
    for (int i = 0; i < N; i++)
    {
        std::scanf("%lld", &C[i]);
    }
    solve(N, A, B, std::move(C));
    return 0;
}
