#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

const string YES = "Yes";
const string NO = "No";

// input format
// H, W
// A11, ..., A1W
// ...
// AH1, ..., AHW
// B11, ..., B1W
// ...
// BH1, ..., BHW
// each element is # or .

// input data from standard input
void solution()
{
    // input data
    int H, W;
    cin >> H >> W;
    vector<vector<char>> A(H, vector<char>(W));
    vector<vector<char>> B(H, vector<char>(W));
    for (int i = 0; i < H; i++)
    {
        for (int j = 0; j < W; j++)
        {
            cin >> A[i][j];
        }
    }
    for (int i = 0; i < H; i++)
    {
        for (int j = 0; j < W; j++)
        {
            cin >> B[i][j];
        }
    }
    // solution
    bool answer = false;
    for (int h = 0; h < H; h++)
    {
        for (int w = 0; w < W; w++)
        {
            if (answer)
            {
                break;
            }
            bool match = true;
            for (int i = 0; i < H; i++)
            {
                for (int j = 0; j < W; j++)
                {
                    match &= (A[i][j] == B[(i + h) % H][(j + w) % W]);
                }
            }
            if (match)
            {
                answer = true;
            }
        }
    }
    cout << (answer ? YES : NO) << endl;
}

//

// Generated by 2.14.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main()
{
    solution();
    return 0;
}
